### ISSUE TITLE
CMake Error: A required package was not found(compiz-0.9.7.8)

### ISSUE THREAD

**Issue by deterok** [BlueDragonX/fm-overlay#3]
...
-- Found the KDE4 kconfig_compiler preprocessor: /usr/bin/kconfig_compiler
-- Found automoc4: /usr/bin/automoc4
-- checking for modules 'xig-0;glib-2.0;gobject-2.0'
--   package 'xig-0' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:266 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  src/timer/CMakeLists.txt:1 (pkg_check_modules)
...
-- Configuring incomplete, errors occurred!
 * ERROR: x11-wm/compiz-0.9.7.8 failed (configure phase):
 *   cmake failed
 * 
 * Call stack:
 *     ebuild.sh, line   85:  Called src_configure
 *   environment, line 3051:  Called cmake-utils_src_configure
 *   environment, line  828:  Called _execute_optionaly 'src_configure'
 *   environment, line  350:  Called enable_cmake-utils_src_configure
 *   environment, line 1129:  Called die

**Comment by BlueDragonX** [comment]
No more Compiz!
